# Generated by Django 3.2 on 2021-05-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_employer',
        ),
    ]
