# Generated by Django 3.2 on 2021-05-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibition_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('heykel', 'HEYKEL'), ('resim', 'RESİM'), ('deri', 'DERİ'), ('cini', 'ÇİNİ'), ('fotograf', 'FOROĞRAF')], default='resim', max_length=20)),
                ('click_counter', models.IntegerField(default=0)),
                ('picture_url', models.ImageField(upload_to='pieces/')),
                ('price', models.CharField(default='Belirtilmemiş', max_length=20)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
