# Generated by Django 3.1.7 on 2021-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('resim', 'RESİM'), ('fotograf', 'FOROĞRAF'), ('heykel', 'HEYKEL'), ('deri', 'DERİ'), ('cini', 'ÇİNİ')], default='resim', max_length=20),
        ),
    ]
