# Generated by Django 3.1.7 on 2021-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_auto_20210523_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('fotograf', 'FOROĞRAF'), ('deri', 'DERİ'), ('cini', 'ÇİNİ'), ('resim', 'RESİM'), ('heykel', 'HEYKEL')], default='resim', max_length=20),
        ),
    ]
