# Generated by Django 3.2 on 2021-05-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_auto_20210529_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('fotograf', 'FOROĞRAF'), ('deri', 'DERİ'), ('heykel', 'HEYKEL'), ('cini', 'ÇİNİ'), ('resim', 'RESİM')], default='resim', max_length=20),
        ),
    ]
