# Generated by Django 3.2 on 2021-05-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_alter_pieces_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('cini', 'ÇİNİ'), ('resim', 'RESİM'), ('fotograf', 'FOROĞRAF'), ('heykel', 'HEYKEL'), ('deri', 'DERİ')], default='resim', max_length=20),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
