# Generated by Django 3.2 on 2021-05-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0006_auto_20210530_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('deri', 'DERİ'), ('cini', 'ÇİNİ'), ('heykel', 'HEYKEL'), ('resim', 'RESİM'), ('fotograf', 'FOROĞRAF')], default='resim', max_length=20),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='release_date',
            field=models.DateField(),
        ),
    ]
