# Generated by Django 3.2 on 2021-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0007_auto_20210530_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('fotograf', 'FOROĞRAF'), ('cini', 'ÇİNİ'), ('heykel', 'HEYKEL'), ('resim', 'RESİM'), ('deri', 'DERİ')], default='resim', max_length=20),
        ),
    ]
