# Generated by Django 3.2 on 2021-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0008_alter_pieces_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('heykel', 'HEYKEL'), ('cini', 'ÇİNİ'), ('deri', 'DERİ'), ('resim', 'RESİM'), ('fotograf', 'FOROĞRAF')], default='resim', max_length=20),
        ),
    ]
