# Generated by Django 3.2 on 2021-06-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0009_alter_pieces_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('heykel', 'HEYKEL'), ('cini', 'ÇİNİ'), ('fotograf', 'FOROĞRAF'), ('deri', 'DERİ'), ('resim', 'RESİM')], default='resim', max_length=20),
        ),
    ]
