# Generated by Django 3.2 on 2021-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0010_alter_pieces_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('cam', 'CAM'), ('resim', 'RESİM'), ('seramik', 'SERAMİK'), ('oymacılık', 'OYMACILIK'), ('fotograf', 'FOTOĞRAF'), ('ebru', 'EBRU'), ('cini', 'ÇİNİ'), ('deri', 'DERİ'), ('heykel', 'HEYKEL')], default='resim', max_length=20),
        ),
    ]
