# Generated by Django 3.2 on 2021-06-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0011_alter_pieces_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('resim', 'RESİM'), ('deri', 'DERİ'), ('ebru', 'EBRU'), ('heykel', 'HEYKEL'), ('fotograf', 'FOTOĞRAF'), ('cini', 'ÇİNİ'), ('seramik', 'SERAMİK'), ('oymacılık', 'OYMACILIK'), ('cam', 'CAM')], default='resim', max_length=20),
        ),
    ]
