# Generated by Django 3.1.7 on 2021-06-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0012_alter_pieces_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('deri', 'DERİ'), ('resim', 'RESİM'), ('cini', 'ÇİNİ'), ('heykel', 'HEYKEL'), ('oymacılık', 'OYMACILIK'), ('ebru', 'EBRU'), ('cam', 'CAM'), ('fotograf', 'FOTOĞRAF'), ('seramik', 'SERAMİK')], default='resim', max_length=20),
        ),
    ]
