# Generated by Django 3.1.7 on 2021-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0014_auto_20210608_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('ebru', 'EBRU'), ('oymacılık', 'OYMACILIK'), ('fotograf', 'FOTOĞRAF'), ('seramik', 'SERAMİK'), ('cini', 'ÇİNİ'), ('cam', 'CAM'), ('resim', 'RESİM'), ('heykel', 'HEYKEL'), ('deri', 'DERİ')], default='resim', max_length=20),
        ),
    ]
