# Generated by Django 3.1.7 on 2021-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0019_auto_20210608_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('deri', 'DERİ'), ('cini', 'ÇİNİ'), ('ebru', 'EBRU'), ('seramik', 'SERAMİK'), ('cam', 'CAM'), ('resim', 'RESİM'), ('oymacılık', 'OYMACILIK'), ('fotograf', 'FOTOĞRAF'), ('heykel', 'HEYKEL')], default='resim', max_length=20),
        ),
    ]
