# Generated by Django 3.1.7 on 2021-06-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0020_auto_20210608_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='category',
            field=models.CharField(choices=[('heykel', 'HEYKEL'), ('deri', 'DERİ'), ('fotograf', 'FOTOĞRAF'), ('cini', 'ÇİNİ'), ('ebru', 'EBRU'), ('seramik', 'SERAMİK'), ('oymacılık', 'OYMACILIK'), ('resim', 'RESİM'), ('cam', 'CAM')], default='resim', max_length=20),
        ),
    ]
