# Generated by Django 3.1.7 on 2021-05-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0002_rename_exhbid_piecepermissions_exh_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecepermissions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
