# Generated by Django 3.1.7 on 2021-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0003_auto_20210523_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecepermissions',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
