# Generated by Django 3.2 on 2021-05-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0004_piecepermissions_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecepermissions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
