# Generated by Django 3.2 on 2021-06-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_data', '0006_comments_follows_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('painting', models.IntegerField(default=0)),
                ('sculpture', models.IntegerField(default=0)),
                ('photograph', models.IntegerField(default=0)),
                ('tile', models.IntegerField(default=0)),
                ('leather', models.IntegerField(default=0)),
                ('ceramic', models.IntegerField(default=0)),
                ('carving', models.IntegerField(default=0)),
                ('glass', models.IntegerField(default=0)),
                ('marbling', models.IntegerField(default=0)),
            ],
        ),
    ]
