# Generated by Django 3.1.7 on 2021-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('owner_id', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(upload_to='exhibitions/thumbnails')),
            ],
        ),
    ]
